# Generated by Django 2.1 on 2021-04-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='field',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
